spring:
  # MySQL 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL驱动
    url: jdbc:mysql://localhost:3306/demobase?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root # 数据库连接名
    password: 5980010 # 数据库连接密码


  favicon:
      enabled: false

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.domain.bean
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  type-enums-package: com.example.demo.domain.enums


